version: "3.8"

services:
  lightningd:
    build: .
    volumes:
      - ./data:/lnmetrics/.lnmetrics
    network_mode: "host"
    environment:
      - SERVER_PORT=8081
      - DB_PATH=/lnmetrics/.lnmetrics
      - BACKEND_PATH=https://127.0.0.1:7000
      - METRICS_LOG=/lnmetrics/.lnmetrics
