// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MetricOne struct {
	Name     string    `json:"name"`
	NodeID   string    `json:"nodeID"`
	Color    string    `json:"color"`
	OsInfo   *OSInfo   `json:"osInfo"`
	Timezone int       `json:"timezone"`
	UpTime   []*Status `json:"upTime"`
}

type NodeInfo struct {
	NodeID    string     `json:"nodeID"`
	MetricOne *MetricOne `json:"metricOne"`
}

type NodeMetrics struct {
	NodeID           string `json:"nodeID"`
	PayloadMetricOne string `json:"payloadMetricOne"`
}

type OSInfo struct {
	Os           string `json:"os"`
	Version      string `json:"version"`
	Architecture string `json:"architecture"`
}

type Status struct {
	Event string `json:"event"`
}
