// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChannelStatus struct {
	Timestamp int    `json:"timestamp"`
	Status    string `json:"status"`
}

type ChannelSummary struct {
	NodeID    string `json:"node_id"`
	Alias     string `json:"alias"`
	Color     string `json:"color"`
	ChannelID string `json:"channel_id"`
	State     string `json:"state"`
}

type ChannelsSummary struct {
	TotChannels int               `json:"tot_channels"`
	Summary     []*ChannelSummary `json:"summary"`
}

type MetricOne struct {
	Name         string           `json:"metric_name"`
	NodeID       string           `json:"node_id"`
	Color        string           `json:"color"`
	NodeAlias    string           `json:"node_alias"`
	Network      *string          `json:"network"`
	OSInfo       *OSInfo          `json:"os_info"`
	NodeInfo     *NodeImpInfo     `json:"node_info"`
	Address      []*NodeAddress   `json:"address"`
	Timezone     string           `json:"timezone"`
	LastUpdate   int              `json:"last_update"`
	UpTime       []*Status        `json:"up_time"`
	ChannelsInfo []*StatusChannel `json:"channels_info"`
	Version      *int             `json:"version"`
}

type NodeAddress struct {
	Type string `json:"type"`
	Host string `json:"host"`
	Port int    `json:"port"`
}

type NodeImpInfo struct {
	Implementation string `json:"implementation"`
	Version        string `json:"version"`
}

type NodeInfo struct {
	NodeID    string     `json:"node_id"`
	MetricOne *MetricOne `json:"metric_one"`
}

type NodeMetadata struct {
	NodeID   string         `json:"node_id"`
	Alias    string         `json:"alias"`
	Color    string         `json:"color"`
	Address  []*NodeAddress `json:"address"`
	OSInfo   *OSInfo        `json:"os_info"`
	NodeInfo *NodeImpInfo   `json:"node_info"`
}

type NodeMetric struct {
	Timestamp    int              `json:"timestamp"`
	UpTime       []*Status        `json:"up_time"`
	ChannelsInfo []*StatusChannel `json:"channels_info"`
}

type NodeMetrics struct {
	NodeID           string `json:"node_id"`
	PayloadMetricOne string `json:"payload_metric_one"`
}

type OSInfo struct {
	Os           string `json:"os"`
	Version      string `json:"version"`
	Architecture string `json:"architecture"`
}

type PaymentInfo struct {
	Direction     string  `json:"direction"`
	Status        string  `json:"status"`
	FailureReason *string `json:"failure_reason"`
	FailureCode   *int    `json:"failure_code"`
}

type PaymentsSummary struct {
	Completed int `json:"completed"`
	Failed    int `json:"failed"`
}

type Status struct {
	Event     string           `json:"event"`
	Channels  *ChannelsSummary `json:"channels"`
	Forwards  *PaymentsSummary `json:"forwards"`
	Timestamp int              `json:"timestamp"`
}

type StatusChannel struct {
	NodeID     string           `json:"node_id"`
	NodeAlias  string           `json:"node_alias"`
	Color      string           `json:"color"`
	Capacity   int              `json:"capacity"`
	Forwards   []*PaymentInfo   `json:"forwards"`
	UpTimes    []*ChannelStatus `json:"up_times"`
	Online     bool             `json:"online"`
	LastUpdate int              `json:"last_update"`
	Public     bool             `json:"public"`
	Direction  string           `json:"direction"`
}
